### ISSUE TITLE
HttpPartConfig retrieves from cache almost always fails

### ISSUE THREAD

**Issue by lloydmeta** [m3dev/octoparts#118]
After adding in Zipkin tracing, I realised that for Octoparts requests w/ multiple part requests, we are almost always failing to get any config info from cache and always hitting the DB.

Looking at logs, this is not the result of timeout errors

```
$cat application.log | grep "Cache retrieve timed out for this identifier" | wc -l 
115
```

Rather, they are the result of failure to deserialise the cached response
```
$ cat application.log | grep "Cache retrieve this identifier" | wc -l
162582
# run within seconds of each other
$ cat application.log | grep "Cache retrieve this identifier" | wc -l
163194
```

Snippet
```
java.io.InvalidClassException: com.m3.octoparts.model.config.HttpPartConfig; local class incompatible: stream classdesc serialVersionUID = -7771707228188004305, local class serialVersionUID = 9192569976570680843
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:621) ~[na:1.8.0_20]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623) ~[na:1.8.0_20]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518) ~[na:1.8.0_20]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774) ~[na:1.8.0_20]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_20]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993) ~[na:1.8.0_20]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918) ~[na:1.8.0_20]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_20]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_20]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_20]
	at shade.memcached.MemcachedCodecs$GenericCodec$$anonfun$deserialize$1$$anonfun$apply$2.apply(Codec.scala:134) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at shade.memcached.MemcachedCodecs$GenericCodec$$anonfun$deserialize$1$$anonfun$apply$2.apply(Codec.scala:133) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at shade.memcached.MemcachedCodecs$Generi
```

**Comment by lloydmeta** [comment]
Valid lines:

https://github.com/m3dev/octoparts/blob/develop/app/com/m3/octoparts/repository/CachingRepository.scala#L99-L105

**Comment by lloydmeta** [comment]
Flushing the Memcached cache manually seems to have fixed it, meaning that maybe our reload cache on app start up isn't properly cleaning up old entries?

**Comment by lloydmeta** [comment]
I think I may have found the culprit:

```
time:2015-03-04 12:03:03,037	level:ERROR	thread:ForkJoinPool-3-worker-3	logger:application	location:CachingRepository.scala:38	hostname:opqa1.office.so-netm3.com	Cache put:HttpPartConfigCacheKey(announcement:confirm:save)
java.io.NotSerializableException: sun.nio.cs.UTF_8
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[na:1.8.0_20]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_20]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_20]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_20]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_20]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_20]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_20]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_20]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_20]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_20]
	at shade.memcached.MemcachedCodecs$GenericCodec$$anonfun$serialize$1$$anonfun$apply$1.apply(Codec.scala:113) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at shade.memcached.MemcachedCodecs$GenericCodec$$anonfun$serialize$1$$anonfun$apply$1.apply(Codec.scala:112) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at shade.memcached.MemcachedCodecs$GenericCodec.using(Codec.scala:104) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at shade.memcached.MemcachedCodecs$GenericCodec$$anonfun$serialize$1.apply(Codec.scala:112) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at shade.memcached.MemcachedCodecs$GenericCodec$$anonfun$serialize$1.apply(Codec.scala:111) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at shade.memcached.MemcachedCodecs$GenericCodec.using(Codec.scala:104) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at shade.memcached.MemcachedCodecs$GenericCodec.serialize(Codec.scala:111) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at shade.memcached.MemcachedCodecs$GenericCodec.serialize(Codec.scala:99) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at shade.memcached.MemcachedImpl.set(MemcachedImpl.scala:60) ~[com.bionicspirit.shade_2.11-1.6.0.jar:1.6.0]
	at com.m3.octoparts.cache.memcached.MemcachedRawCache.set(MemcachedRawCache.scala:23) ~[com.m3.octoparts-m3-2.4.1-SNAPSHOT.jar:2.4.1-SNAPSHOT]
	at com.m3.octoparts.cache.LoggingRawCache.set(LoggingRawCache.scala:25) ~[com.m3.octoparts-m3-2.4.1-SNAPSHOT.jar:2.4.1-SNAPSHOT]
	at com.m3.octoparts.cache.MemoryBufferingRawCache.set(MemoryBufferingRawCache.scala:38) ~[com.m3.octoparts-m3-2.4.1-SNAPSHOT.jar:2.4.1-SNAPSHOT]
	at com.m3.octoparts.cache.memcached.MemcachedCache.put(MemcachedCache.scala:59) ~[
```

**Comment by lloydmeta** [comment]
Fairly certain at this point that this is caused by the new charset field added in #112

**Comment by lloydmeta** [comment]
Testing shows that #120 fixes this issue. Closing now.
