### ISSUE TITLE
Connection pool tests consistently failing

### ISSUE THREAD

**Issue by xevix** [m3dev/octoparts#194]
The bottom result is from `testOnly com.m3.octoparts.database.MigrationsSpec` but the following failed:

```
[info] *** 1 SUITE ABORTED ***
[info] *** 3 TESTS FAILED ***
[error] Error: Total 290, Failed 3, Errors 1, Passed 286
[error] Failed tests:
[error]     com.m3.octoparts.future.RichFutureWithTimingSpec
[error]     com.m3.octoparts.database.MigrationsSpec
[error] Error during tests:
[error]     com.m3.octoparts.repository.config.CacheGroupRepositorySpec
[error] (octoparts/test:test) sbt.TestsFailedException: Tests unsuccessful
```

This is running tests from within vaygrant, and from without. In neither case was Octoparts running in the background in a separate terminal.

```
[info] MigrationsSpec:
[info] Running migrations
[info]   from an empty database
2016-02-08 05:32:31,402 ERROR [pool-1-thread-1-ScalaTest-running-MigrationsSpec] application [RequiresDB.scala:79] 
java.lang.IllegalStateException: Connection pool is not yet initialized.(name:'default)
    at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:57) ~[scalikejdbc-core_2.11-2.3.0.jar:2.3.0]
    at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:55) ~[scalikejdbc-core_2.11-2.3.0.jar:2.3.0]
    at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:na]
    at scalikejdbc.ConnectionPool$.get(ConnectionPool.scala:55) ~[scalikejdbc-core_2.11-2.3.0.jar:2.3.0]
    at scalikejdbc.ConnectionPool$.apply(ConnectionPool.scala:46) ~[scalikejdbc-core_2.11-2.3.0.jar:2.3.0]
    at com.m3.octoparts.support.db.RequiresDB$class.flyway(RequiresDB.scala:57) ~[test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec.flyway$lzycompute(MigrationsSpec.scala:6) [test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec.flyway(MigrationsSpec.scala:6) [test-classes/:na]
    at com.m3.octoparts.support.db.RequiresDB$class.tearDown(RequiresDB.scala:77) ~[test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec.tearDown(MigrationsSpec.scala:6) [test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(MigrationsSpec.scala:11) [test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(MigrationsSpec.scala:10) [test-classes/:na]
    at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(MigrationsSpec.scala:10) [test-classes/:na]
    at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.Transformer.apply(Transformer.scala:22) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.Transformer.apply(Transformer.scala:20) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:422) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.Suite$class.withFixture(Suite.scala:1122) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpec.withFixture(FunSpec.scala:1626) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:419) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:431) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpec.runTest(FunSpec.scala:1626) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:381) [scala-library-2.11.7.jar:na]
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:381) [scala-library-2.11.7.jar:na]
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:381) [scala-library-2.11.7.jar:na]
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:464) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpec.runTests(FunSpec.scala:1626) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.Suite$class.run(Suite.scala:1424) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1626) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.SuperEngine.runImpl(Engine.scala:545) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:468) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.FunSpec.run(FunSpec.scala:1626) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357) [scalatest_2.11-2.2.6.jar:na]
    at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502) [scalatest_2.11-2.2.6.jar:na]
    at sbt.ForkMain$Run$2.call(ForkMain.java:296) [test-agent-0.13.9.jar:0.13.9]
    at sbt.ForkMain$Run$2.call(ForkMain.java:286) [test-agent-0.13.9.jar:0.13.9]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
[info]   - should not fail *** FAILED ***
[info]     java.lang.IllegalStateException: Connection pool is not yet initialized.(name:'default)
[info]     at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:57)
[info]     at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:55)
[info]     at scala.Option.getOrElse(Option.scala:121)
[info]     at scalikejdbc.ConnectionPool$.get(ConnectionPool.scala:55)
[info]     at scalikejdbc.ConnectionPool$.apply(ConnectionPool.scala:46)
[info]     at com.m3.octoparts.support.db.RequiresDB$class.flyway(RequiresDB.scala:57)
[info]     at com.m3.octoparts.database.MigrationsSpec.flyway$lzycompute(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.database.MigrationsSpec.flyway(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.support.db.RequiresDB$class.migrate(RequiresDB.scala:87)
[info]     at com.m3.octoparts.database.MigrationsSpec.migrate(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(MigrationsSpec.scala:12)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(MigrationsSpec.scala:10)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(MigrationsSpec.scala:10)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]     at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:422)
[info]     at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]     at org.scalatest.FunSpec.withFixture(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:419)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431)
[info]     at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]     at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:431)
[info]     at org.scalatest.FunSpec.runTest(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]     at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]     at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:464)
[info]     at org.scalatest.FunSpec.runTests(FunSpec.scala:1626)
[info]     at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]     at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468)
[info]     at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468)
[info]     at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]     at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:468)
[info]     at org.scalatest.FunSpec.run(FunSpec.scala:1626)
[info]     at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
[info]     at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
[info]     at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]     at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]     at java.lang.Thread.run(Thread.java:745)
[info]   from a fully migrated database
[info]   - should not fail *** FAILED ***
[info]     java.lang.IllegalStateException: Connection pool is not yet initialized.(name:'default)
[info]     at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:57)
[info]     at scalikejdbc.ConnectionPool$$anonfun$get$1.apply(ConnectionPool.scala:55)
[info]     at scala.Option.getOrElse(Option.scala:121)
[info]     at scalikejdbc.ConnectionPool$.get(ConnectionPool.scala:55)
[info]     at scalikejdbc.ConnectionPool$.apply(ConnectionPool.scala:46)
[info]     at com.m3.octoparts.support.db.RequiresDB$class.flyway(RequiresDB.scala:57)
[info]     at com.m3.octoparts.database.MigrationsSpec.flyway$lzycompute(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.database.MigrationsSpec.flyway(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.support.db.RequiresDB$class.migrate(RequiresDB.scala:87)
[info]     at com.m3.octoparts.database.MigrationsSpec.migrate(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply$mcV$sp(MigrationsSpec.scala:18)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply(MigrationsSpec.scala:17)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply(MigrationsSpec.scala:17)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]     at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:422)
[info]     at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]     at org.scalatest.FunSpec.withFixture(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:419)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:431)
[info]     at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]     at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:431)
[info]     at org.scalatest.FunSpec.runTest(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464)
[info]     at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:464)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]     at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]     at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:464)
[info]     at org.scalatest.FunSpec.runTests(FunSpec.scala:1626)
[info]     at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]     at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1626)
[info]     at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468)
[info]     at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:468)
[info]     at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]     at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:468)
[info]     at org.scalatest.FunSpec.run(FunSpec.scala:1626)
[info]     at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
[info]     at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
[info]     at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]     at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]     at java.lang.Thread.run(Thread.java:745)
[info] ScalaTest
[info] Run completed in 8 seconds, 752 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
```

**Comment by lloydmeta** [comment]
Nice find :)
