### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by seratch** [m3dev/octoparts#199]
```
octoparts:bump-sbt:2.6.1-SNAPSHOT> dependencyUpdates
[info] Found 5 dependency updates for octoparts-models
[info]   com.fasterxml.jackson.core:jackson-core              : 2.5.1  -> 2.5.5  -> 2.8.3
[info]   com.fasterxml.jackson.module:jackson-module-scala    : 2.5.1  -> 2.5.2  -> 2.8.3
[info]   com.wordnik:swagger-annotations                      : 1.3.12 -> 1.3.13
[info]   org.scoverage:scalac-scoverage-plugin_2.11:provided  : 1.0.4            -> 1.2.0
[info]   org.scoverage:scalac-scoverage-runtime_2.11:provided : 1.0.4            -> 1.2.0
[info] Found 4 dependency updates for octoparts-scala-ws-client
[info]   com.typesafe.play:play-ws                            : 2.4.6 -> 2.4.8 -> 2.5.8
[info]   org.scalatest:scalatest:test                         : 2.2.6                   -> 3.0.0
[info]   org.scoverage:scalac-scoverage-plugin_2.11:provided  : 1.0.4          -> 1.2.0
[info]   org.scoverage:scalac-scoverage-runtime_2.11:provided : 1.0.4          -> 1.2.0
[info] Found 4 dependency updates for octoparts-play-json-formats
[info]   com.typesafe.play:play-json                          : 2.4.6 -> 2.4.8 -> 2.5.8
[info]   org.scalatest:scalatest:test                         : 2.2.6                   -> 3.0.0
[info]   org.scoverage:scalac-scoverage-plugin_2.11:provided  : 1.0.4          -> 1.2.0
[info]   org.scoverage:scalac-scoverage-runtime_2.11:provided : 1.0.4          -> 1.2.0
[info] Found 14 dependency updates for octoparts-java-client
[info]   ch.qos.logback:logback-classic:test                  : 1.1.3  -> 1.1.7
[info]   com.fasterxml.jackson.core:jackson-core              : 2.5.1  -> 2.5.5  -> 2.8.3
[info]   com.fasterxml.jackson.core:jackson-databind          : 2.5.1  -> 2.5.5  -> 2.8.3
[info]   com.fasterxml.jackson.module:jackson-module-scala    : 2.5.1  -> 2.5.2  -> 2.8.3
[info]   com.google.code.findbugs:jsr305                      : 3.0.0  -> 3.0.1
[info]   com.google.guava:guava                               : 18.0                      -> 19.0
[info]   com.ning:async-http-client                           : 1.9.21 -> 1.9.39
[info]   org.scalatest:scalatest:test                         : 2.2.6                     -> 3.0.0
[info]   org.scoverage:scalac-scoverage-plugin_2.11:provided  : 1.0.4            -> 1.2.0
[info]   org.scoverage:scalac-scoverage-runtime_2.11:provided : 1.0.4            -> 1.2.0
[info]   org.slf4j:jcl-over-slf4j                             : 1.7.10 -> 1.7.21
[info]   org.slf4j:jul-to-slf4j                               : 1.7.10 -> 1.7.21
[info]   org.slf4j:log4j-over-slf4j                           : 1.7.10 -> 1.7.21
[info]   org.slf4j:slf4j-api                                  : 1.7.10 -> 1.7.21
[info] Found 3 dependency updates for octoparts-auth-handler-api
[info]   com.typesafe.play:play:provided                      : 2.4.6 -> 2.4.8 -> 2.5.8
[info]   org.scoverage:scalac-scoverage-plugin_2.11:provided  : 1.0.4          -> 1.2.0
[info]   org.scoverage:scalac-scoverage-runtime_2.11:provided : 1.0.4          -> 1.2.0
[info] Found 34 dependency updates for octoparts
[info]   ch.qos.logback:logback-classic                       : 1.1.3           -> 1.1.7
[info]   com.bionicspirit:shade                               : 1.7.2           -> 1.7.4
[info]   com.netaporter:scala-uri                             : 0.4.6           -> 0.4.15
[info]   com.netflix.hystrix:hystrix-core                     : 1.4.23          -> 1.4.26   -> 1.5.6
[info]   com.netflix.hystrix:hystrix-metrics-event-stream     : 1.4.23          -> 1.4.26   -> 1.5.6
[info]   com.softwaremill.macwire:macros                      : 2.2.1           -> 2.2.4
[info]   com.typesafe.play:play-netty-server                  : 2.4.6           -> 2.4.8    -> 2.5.8
[info]   com.typesafe.play:play-omnidoc:docs                  : 2.4.6           -> 2.4.8    -> 2.5.8
[info]   com.typesafe.play:play-server                        : 2.4.6           -> 2.4.8    -> 2.5.8
[info]   com.typesafe.play:play-test:test                     : 2.4.6           -> 2.4.8    -> 2.5.8
[info]   com.typesafe.play:play-test:test                     : 2.4.6           -> 2.4.8    -> 2.5.8
[info]   com.typesafe.play:play-ws                            : 2.4.6           -> 2.4.8    -> 2.5.8
[info]   com.typesafe.play:twirl-api                          : 1.1.1                       -> 1.2.0
[info]   commons-validator:commons-validator:runtime          : 1.4.1                       -> 1.5.1
[info]   io.reactivex:rxscala                                 : 0.26.0          -> 0.26.2
[info]   org.apache.httpcomponents:httpclient                 : 4.5.1           -> 4.5.2
[info]   org.apache.httpcomponents:httpclient-cache           : 4.5.1           -> 4.5.2
[info]   org.codehaus.groovy:groovy:test                      : 2.4.1           -> 2.4.7
[info]   org.codehaus.janino:janino                           : 2.7.8                                 -> 3.0.6
[info]   org.flywaydb:flyway-play                             : 2.2.0           -> 2.2.1    -> 2.3.0  -> 3.0.1
[info]   org.postgresql:postgresql:runtime                    : 9.4-1201-jdbc41 -> 9.4.1211
[info]   org.scalacheck:scalacheck:test                       : 1.12.2          -> 1.12.5   -> 1.13.2
[info]   org.scalatest:scalatest:test                         : 2.2.6                                 -> 3.0.0
[info]   org.scalikejdbc:scalikejdbc                          : 2.3.0           -> 2.3.5    -> 2.4.2
[info]   org.scalikejdbc:scalikejdbc-config                   : 2.3.0           -> 2.3.5    -> 2.4.2
[info]   org.scalikejdbc:scalikejdbc-play-initializer         : 2.4.3           -> 2.4.5    -> 2.5.1
[info]   org.scalikejdbc:scalikejdbc-test:test                : 2.3.0           -> 2.3.5    -> 2.4.2
[info]   org.scoverage:scalac-scoverage-plugin_2.11:provided  : 1.0.4                       -> 1.2.0
[info]   org.scoverage:scalac-scoverage-runtime_2.11:provided : 1.0.4                       -> 1.2.0
[info]   org.skinny-framework:skinny-orm                      : 2.0.1           -> 2.0.9    -> 2.2.0
[info]   org.slf4j:jcl-over-slf4j                             : 1.7.10          -> 1.7.21
[info]   org.slf4j:jul-to-slf4j                               : 1.7.10          -> 1.7.21
[info]   org.slf4j:log4j-over-slf4j                           : 1.7.10          -> 1.7.21
[info]   org.slf4j:slf4j-api                                  : 1.7.10          -> 1.7.21
```

**Comment by seratch** [comment]
I found several issues on upgrading the following libraries.

## ScalaTest 3.0

We just need to fix the compilation errors.

```
[error] /Users/kazuhirosera/github/oss/octoparts/test/com/m3/octoparts/support/SpecHarnesses.scala:175: not found: type NoArgTest
[error]   abstract override def withFixture(test: NoArgTest): Outcome = {
[error]                                           ^
[error] /Users/kazuhirosera/github/oss/octoparts/test/com/m3/octoparts/support/SpecHarnesses.scala:182: value withFixture is not a member of org.scalatest.SuiteMixin with org.scalatest.selenium.WebBrowser with org.scalatest.concurrent.Eventually with org.scalatest.concurrent.IntegrationPatience with org.scalatestplus.play.BrowserFactory
[error]       case _ => super.withFixture(test)
[error]                       ^
[error] /Users/kazuhirosera/github/oss/octoparts/test/com/m3/octoparts/support/SpecHarnesses.scala:210: type mismatch;
[error]  found   : Boolean => Unit
[error]  required: scala.util.Try[Boolean] => Unit
[error]       status.whenCompleted(cleanup)
[error]                            ^
[error] /Users/kazuhirosera/github/oss/octoparts/test/com/m3/octoparts/support/db/AutoRollback2.scala:33: not found: type OneArgTest
[error]   override def withFixture(test: OneArgTest): Outcome = {
[error]                                  ^
```

## Flyway 4.0

Runtime errors. I couldn't figure out the root cause of this issue yet.

```
[info]   - should not fail *** FAILED ***
[info]     org.flywaydb.core.api.FlywayException: Unable to commit transaction
[info]     at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:76)
[info]     at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:136)
[info]     at org.flywaydb.core.Flyway.doValidate(Flyway.java:1002)
[info]     at org.flywaydb.core.Flyway.access$100(Flyway.java:72)
[info]     at org.flywaydb.core.Flyway$1.execute(Flyway.java:921)
[info]     at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
[info]     at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
[info]     at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
[info]     at com.m3.octoparts.support.db.RequiresDB$class.migrate(RequiresDB.scala:89)
[info]     at com.m3.octoparts.database.MigrationsSpec.migrate(MigrationsSpec.scala:6)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply$mcV$sp(MigrationsSpec.scala:18)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply(MigrationsSpec.scala:17)
[info]     at com.m3.octoparts.database.MigrationsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply(MigrationsSpec.scala:17)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
```
